// generated by stringer -type=itemType; DO NOT EDIT

package mips

import "fmt"

const (
	_itemType_name_0 = "itemEOFitemError"
	_itemType_name_1 = "itemInst"
	_itemType_name_2 = "itemLabel"
	_itemType_name_3 = "itemDir"
)

var (
	_itemType_index_0 = [...]uint8{0, 7, 16}
	_itemType_index_1 = [...]uint8{0, 8}
	_itemType_index_2 = [...]uint8{0, 9}
	_itemType_index_3 = [...]uint8{0, 7}
)

func (i itemType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _itemType_name_0[_itemType_index_0[i]:_itemType_index_0[i+1]]
	case i == 4:
		return _itemType_name_1
	case i == 8:
		return _itemType_name_2
	case i == 16:
		return _itemType_name_3
	default:
		return fmt.Sprintf("itemType(%d)", i)
	}
}
