// generated by stringer -type=tokenType; DO NOT EDIT

package asm

import "fmt"

const _tokenType_name = "tokenErrortokenEOFtokenInstructiontokenIntegertokenRegistertokenCommatokenColontokenBytetokenStringtokenDirectivetokenLeftParenthesetokenRightParenthesetokenLabeltokenLabelDeftokenEndline"

var _tokenType_map = map[tokenType]string{
	2:     _tokenType_name[0:10],
	4:     _tokenType_name[10:18],
	8:     _tokenType_name[18:34],
	16:    _tokenType_name[34:46],
	32:    _tokenType_name[46:59],
	64:    _tokenType_name[59:69],
	128:   _tokenType_name[69:79],
	256:   _tokenType_name[79:88],
	512:   _tokenType_name[88:99],
	1024:  _tokenType_name[99:113],
	2048:  _tokenType_name[113:132],
	4096:  _tokenType_name[132:152],
	8192:  _tokenType_name[152:162],
	16384: _tokenType_name[162:175],
	32768: _tokenType_name[175:187],
}

func (i tokenType) String() string {
	if str, ok := _tokenType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("tokenType(%d)", i)
}
