// generated by stringer -type=ExitStatus; DO NOT EDIT

package mips

import "fmt"

const _ExitStatus_name = "EXIT_NORMALEXIT_INTEXIT_EOFEXIT_ERROR"

var _ExitStatus_index = [...]uint8{0, 11, 19, 27, 37}

func (i ExitStatus) String() string {
	if i < 0 || i+1 >= ExitStatus(len(_ExitStatus_index)) {
		return fmt.Sprintf("ExitStatus(%d)", i)
	}
	return _ExitStatus_name[_ExitStatus_index[i]:_ExitStatus_index[i+1]]
}
